@startuml jissyu4_1
actor ユーザー
boundary ブラウザ
control web.php
control jissyu4_1Controller
boundary input.blade.php
boundary output.blade.php

ユーザー -> ブラウザ : 該当ページをリクエスト[/jissyu6]
ブラウザ -> web.php : GET[/jissyu6]
web.php -> jissyu4_1Controller : @index
jissyu4_1Controller -> input.blade.php
ユーザー -> input.blade.php : 送信ボタンを押下
input.blade.php -> web.php : POST
web.php -> jissyu4_1Controller : @post

alt 成功
jissyu4_1Controller -> output.blade.php
else エラー発生
jissyu4_1Controller -> input.blade.php
end
@enduml